### ISSUE TITLE
Hide version number from admin login page

### ISSUE THREAD

**Issue by chrislaai** [vendurehq/vendure#2428]
Currently we can see the version number on the admin login page, which will reveal the version we are using and may have potential security risks. Can we consider deleting the version number on the admin login page? We can display the version number in the lower right corner of the page or elsewhere after logging in.

**Comment by ashishkpaul** [comment]
https://beta-docs.vendure.io/guides/extending-the-admin-ui/admin-ui-theming-branding/#adminuiplugin-branding-settings

**Comment by ashishkpaul** [comment]
I can understand,  I was on mobile,  that's why I just paste the doc link

**Comment by ashishkpaul** [comment]
"Can we consider deleting the version number on the admin login page?" 
```
import { VendureConfig } from '@vendure/core';
import { AdminUiPlugin } from '@vendure/admin-ui-plugin';

export const config: VendureConfig = {
    // ...
    plugins: [
        AdminUiPlugin.init({
            // ...
            adminUiConfig:{
                brand: 'My Store',
                hideVendureBranding: false,
                hideVersion: true, // ----------------> this will hide the version no
            }
        }),
    ],
};
```
the above snippet can simply hide the version no from the admin login page

**Comment by ashishkpaul** [comment]
> > https://beta-docs.vendure.io/guides/extending-the-admin-ui/admin-ui-theming-branding/#adminuiplugin-branding-settings
> 
> You make me feel like you just read the title and not the content. I'm not asking how to hide the version number for myself. I am suggesting that from a security perspective, we remove the version number from the login page, which is better for everyone.
Okay, the better way to post a query in a Discord channel might be for someone to give you a better overview.

**Comment by oidt** [comment]
Maybe you can make a PR for this? the thought of only seeing the version after login is a good proposal.
For now if you are worried about your own security backend admin. use the solutions @ashishkpaul is giving.
