### ISSUE TITLE
Error verifying Stripe webhook signature after upgrade to 2.1.0

### ISSUE THREAD

**Issue by lzzfnc** [vendurehq/vendure#2450]
**Describe the bug**
After upgrading to 2.1.0, arranging a payment with the stripe plugin crash the server. 

``` 
[server] error 10/13/23, 2:31 PM - [StripePlugin] Error verifying Stripe webhook signature t=1697207506,v1=4702b09d11c0388d6605a6e0f315b3db0e5e91b756cf347de16cc3c5d27e35e2,v0=b8a5a131f5ce8ab3dbfc26849737238b88e9675094c2b16527d94905ef67c569: No webhook payload was provided. 
[server] info 10/13/23, 2:31 PM - [StripePlugin] Stripe payment intent id pi_3O0mOlHJz38WEyqE0LpLgR0z added to order PYCG4ZY3N8EXSZM9 
[server] error 10/13/23, 2:31 PM - [Vendure Server] Cannot set headers after they are sent to the client
[server] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[server]     at new NodeError (node:internal/errors:387:5)
[server]     at ServerResponse.setHeader (node:_http_outgoing:644:11)
[server]     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:794:10)
[server]     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:174:12)
[server]     at StripeController.webhook (/usr/src/app/node_modules/@vendure/payments-plugin/package/stripe/stripe.controller.js:95:49)
[server]     at processTicksAndRejections (node:internal/process/task_queues:96:5) 
[server] node:internal/errors:478
2023[server]     ErrorCaptureStackTrace(err);
[server]     ^
[server] 
```

**To Reproduce**
1. Upgrade to 2.1.0
2. Send a payment with Stripe 
3. See error

**Expected behavior**
The Stripe plugin should be able to verify the webhook signature

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.0
 - Nodejs version 18
 - Database: postgres etc
 - Deployed on Northflank

**Additional context**
Note that in the Stripe dashboard the payment arrives. 

Could probably be related to: https://github.com/vendure-ecommerce/vendure/issues/2444

**Comment by lzzfnc** [comment]
The same procedure test in local still does not work, but it doesn't crash the server nor log any error

**Comment by carathorys** [comment]
I've made a PR in order to avoid the backend crash, but it's just a quick fix for that part. 
The main issue is originated because the `rawBodyMiddleware` doesn't get executed, and the `request.rawBody` is undefined when the `StripeService` treis to validate the payload signature.

**Comment by lzzfnc** [comment]
Hello! Sorry to re-oopen this issue, but after updating to Vendure 2.1.7 the problem showed up again. 
The server is not crashing anymore, just logging the error,

```
2024-02-10T08:27:47.927681237Z stdout F error 2/10/24, 8:27 AM - [StripePlugin] Error verifying Stripe webhook signature t=1707553666,v1=0c1fbecf512418c9cf5f2ed38d72ea33bf4bc7ff1dbf8176e4a136311342b5ec: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? 
```

Current stack is:

- Vendure 2.1.7
- Nodejs version 18
- Database: postgres etc
- Deployed on Northflank
