### ISSUE TITLE
 "facet_value" violates not-null constraint when updating them through the FacetValueService

### ISSUE THREAD

**Issue by Caryntjen** [vendurehq/vendure#2567]
**Describe the bug**
When you update a facetValue with the facetValueService it complains about a not-null constraint

```
  query: 'INSERT INTO "vendure"."facet_value"("createdAt", "updatedAt", "code", "facetId", "customFieldsHexcode", "customFieldsNotes", "customFieldsHaslinkedfacets") VALUES (DEFAULT, DEFAULT, $1, DEFAULT, $2, DEFAULT, DEFAULT) RETURNING "createdAt", "updatedAt", "id", "customFieldsHaslinkedfacets"',
  parameters: [ '38', '212121' ],
  driverError: error: null value in column "facetId" of relation "facet_value" violates not-null constraint
```

**To Reproduce**
Create facet without facetValues through facetService.create().
Create facetValue through: facetValueService.create().
Retrieve facetValues through facetValueService: findByFacetId(ctx, facet.id).
find an existing facetValue you get: find(facetValue => facetValue.code === code)
Update that facetValue through UpdateFacetValueInput where you can give in code, facetValueId, translations and custonfields.

->   driverError: error: null value in column "facetId" of relation "facet_value" violates not-null constraint

During debugging, the UpdateFacetValueInput had an id 2720:
![image](https://github.com/vendure-ecommerce/vendure/assets/3481691/3ec05749-3ba2-4c67-b2e0-057803a8e847)

Also the id is found in the FacetValue tabel:
![image](https://github.com/vendure-ecommerce/vendure/assets/3481691/64e3586c-1c5a-4eb0-b8ad-c09845bce11d)

**Expected behavior**
That the FacetValue is correctly updated

**Environment (please complete the following information):**
 - @vendure/core version: 2.1.4
 - Nodejs version 20.10.0
 - Database (mysql/postgres etc): postgress

**Additional context**
All done programatically through the server in a CLI script.

I did found that a migration generate did add that constraint a while back:

        await queryRunner.query(`ALTER TABLE "vendure"."facet_value" ALTER COLUMN "facetId" SET NOT NULL`, undefined);

I have tried to locate where this was introduced and it is in v2.1.0 I think.

**Comment by michaelbromley** [comment]
Hi, thanks for the report and the reproduction instructions. To make it easier for me to fix, would you be able to provide a minimal script which reproduces the error that I could simply run?

**Comment by Caryntjen** [comment]
@michaelbromley , this is the script I ran on a new Vendure 2.1.4 instance.

`/* eslint-disable */
import {INestApplicationContext} from '@nestjs/common';
import {
    bootstrapWorker,
    ConfigService,
    FacetService,
    FacetValueService, LanguageCode,
    RequestContext,
    RequestContextService,
    TransactionalConnection,
    User,
} from '@vendure/core';
import path from 'path';
import 'reflect-metadata';
import { config } from '../vendure-config';

if (require.main === module) {
    importDataInitialData().then(
        () => process.exit(0),
        err => {
            console.log(err);
            process.exit(1);
        },
    );
}
export type InputMaybe<T> = T;
export type Scalars = {
    ID: { input: string; output: string; }
    String: { input: string; output: string; }
    Boolean: { input: boolean; output: boolean; }
    Int: { input: number; output: number; }
    Float: { input: number; output: number; }
    DateTime: { input: Date; output: string; }
    JSON: { input: any; output: any; }
    Money: { input: number; output: number; }
    Upload: { input: any; output: any; }
};

export type FacetTranslationInput = {
    customFields?: InputMaybe<Scalars['JSON']['input']>;
    id?: InputMaybe<Scalars['ID']['input']>;
    languageCode: LanguageCode;
    name?: InputMaybe<Scalars['String']['input']>;
};

export type CreateFacetValueWithFacetInput = {
    code: Scalars['String']['input'];
    translations: Array<FacetValueTranslationInput>;
};
export type FacetValueTranslationInput = {
    customFields?: InputMaybe<Scalars['JSON']['input']>;
    id?: InputMaybe<Scalars['ID']['input']>;
    languageCode: LanguageCode;
    name?: InputMaybe<Scalars['String']['input']>;
};

export type CreateFacetInput = {
    code: Scalars['String']['input'];
    customFields?: InputMaybe<Scalars['JSON']['input']>;
    isPrivate: Scalars['Boolean']['input'];
    translations: Array<FacetTranslationInput>;
    values?: InputMaybe<Array<CreateFacetValueWithFacetInput>>;
};
export type CreateFacetValueCustomFieldsInput = {
    HEXCode?: InputMaybe<Scalars['String']['input']>;
    hasLinkedFacetValues?: InputMaybe<Scalars['Boolean']['input']>;
    linkedFacetValuesIds?: InputMaybe<Array<Scalars['String']['input']>>;
    notes?: InputMaybe<Scalars['String']['input']>;
};

export type CreateFacetValueInput = {
    code: Scalars['String']['input'];
    customFields?: InputMaybe<CreateFacetValueCustomFieldsInput>;
    facetId: Scalars['ID']['input'];
    translations: Array<FacetValueTranslationInput>;
};

export type UpdateFacetValueInput = {
    code?: InputMaybe<Scalars['String']['input']>;
    customFields?: InputMaybe<UpdateFacetValueCustomFieldsInput>;
    id: Scalars['ID']['input'];
    translations?: InputMaybe<Array<FacetValueTranslationInput>>;
};
export type UpdateFacetValueCustomFieldsInput = {
    HEXCode?: InputMaybe<Scalars['String']['input']>;
    hasLinkedFacetValues?: InputMaybe<Scalars['Boolean']['input']>;
    linkedFacetValuesIds?: InputMaybe<Array<Scalars['String']['input']>>;
    notes?: InputMaybe<Scalars['String']['input']>;
};
async function importDataInitialData() {
    // We use the bootstrapWorker() function instead of bootstrap() because we don't
    // need to start the server, we just need access to the services.
    const {app} = await bootstrapWorker(config);

    // Let's grab a reference to each of the Vendure services we'll need.
    const facetService = app.get(FacetService);
    const facetValueService = app.get(FacetValueService);

    // Most service methods require a RequestContext, so we'll create one here.
    const ctx = await getSuperadminContext(app);

    const facet = await facetService.create(ctx,{
        code: 'facet',
        isPrivate: false,
        translations: [
            {languageCode: LanguageCode.en, name: 'Facet'}
        ],
    });

    const foundFacet = await facetService.findByCode(ctx, 'facet', LanguageCode.en);

    const fv:  CreateFacetValueInput = {
        facetId: foundFacet!.id.toString(),
        code: "facetValueCode",
        translations: [
            { languageCode: LanguageCode.en, name: "FacetVAlue" },
        ]
    }


    const createdFacetValue = await facetValueService.create(ctx, foundFacet!, fv);
    const foundFacetValues = await facetValueService.findByFacetId(ctx, foundFacet!.id);
    const facetValue = foundFacetValues.find(facetValue  => facetValue.code === "facetValueCode");

    let updatedFacetValueInput: UpdateFacetValueInput = {
        id: facetValue!.id.toString(),
        code: facetValue?.code
    };
    const updatedFacetValue = await facetValueService.update(ctx, updatedFacetValueInput);



    // Close the app
    await app.close();
}

/**
 * Creates a RequestContext configured for the default Channel with the activeUser set
 * as the superadmin user.
 */
export async function getSuperadminContext(app: INestApplicationContext): Promise<RequestContext> {
    const {superadminCredentials} = app.get(ConfigService).authOptions;
    const superAdminUser = await app
        .get(TransactionalConnection)
        .rawConnection.getRepository(User)
        .findOneOrFail({where: {identifier: superadminCredentials.identifier}});
    return app.get(RequestContextService).create({
        apiType: 'admin',
        user: superAdminUser,
    });
}`

**Comment by Caryntjen** [comment]
@michaelbromley did this help to reproduce it?

**Comment by michaelbromley** [comment]
Since you are calling an update with `await facetValueService.update(ctx, updatedFacetValueInput);`, but the query in your original error is attempting an `INSERT` rather than an `UPDATE`, this suggests to me that TypeORM is not finding a matching ID and so thinks this is a new entity rather than an existing one.

This is likely cause by the line:

```ts
id: facetValueFromFoundFacetValues!.id.toString(),
```

I understand why you did this - to prevent a TS error. But if you are using the auto increment ID strategy, then the DB will be expecting a number rather than a string. Instead of casting to string, try just asserting it to keep TS happy:

```ts
id: facetValueFromFoundFacetValues!.id as string,
```

**Comment by Caryntjen** [comment]
Okay, indeed this seems to work! Thanks for the input!
